/*
 * MEXTI_Lconfig.c
 *
 *  Created on: Jan 22, 2024
 *      Author: Hassa
 */



#include "MEXTI_config.h"

MEXTI_CFG_t EXTI_PORT[MEXTI_MAX_LINES] =
					   {{MEXTI0_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI1_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI2_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI3_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI4_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI5_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI6_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI7_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI8_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI9_LINE , MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI10_LINE, MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI11_LINE, MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI12_LINE, MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI13_LINE, MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI14_LINE, MEXTI_FAILING_TRIG, DISABLE},
						{MEXTI15_LINE, MEXTI_FAILING_TRIG, DISABLE}};
